[package]
name = "issue_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_flycam = "*"
bevy = { version = "0.12", features = ["dynamic_linking"] }
